### ISSUE TITLE
9.1.1.x Document Naming Convention

### ISSUE THREAD

**Issue by bakerstu** [nmradcc/documents#23]
We currently have mixed naming conventions for these related documents:

9.1.1.1 Six **&** Eight Pin Interface
9.1.1.2 JST 9 Pin Interface
9.1.1.3 21MTC Interface
9.1.1.4 PluX Interface
9.1.1.5 Next 18 **and** Next18-S **Decoder** Interface

In one instance we use "&" while in another instance we use "and".

In one instance we use "Decoder Interface", while in other instances we just use "Interface".

We need to decide which is correct and fix the other(s) for consistency.

**Comment by JuettM** [comment]
I am agreeable to use & rather than and to save a little space. Either would be acceptable I believe. 
However, Decoder Interface is more descriptive than Interface yet requires more letters and I think that would be better.

**Comment by bakerstu** [comment]
Fixed.
