### ISSUE TITLE
Feedback on S-9-1-2 draft

### ISSUE THREAD

**Issue by balazsracz** [nmradcc/documents#3]
Hi,

I have annotated the PDF version of the draft/S-9.1.2 and TN-9.1.2 documents with my comments.
The PDF was downloaded at 7e85fc0aca507d063910144043ad3649a6d2ee6d git hash.

The comments to the standard text are here:
https://drive.google.com/file/d/1xdDxl_yMoBbFqRPNKF-9FYUDf4dSb9ps/view
The comments to the technical note text are here:
https://drive.google.com/file/d/1-pobvjeITla9fHOg1VDBe6vOuBgDmyQi/view

It is possible to discuss the comments individually on the Google Drive comment thread. If someone would like to reply there, let me know (needs a Google account). Stuart has access for inline replies.
 
There are a large number of typos and minor wording suggestions, I propose that we mark these as Resolved if it is incorporated into the github version of the draft document. Afterwards only the content-specific comment threads should be visible. Resolved comments can be accessed by clicking the comment icon on the top right.

thanks
Balazs

**Comment by bakerstu** [comment]
I believe I have applied all relevant feedback from this review.
